name = "chatbot-api"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[env.production]
name = "chatbot-api-prod"

[vars]
NODE_ENV = "production"
SUPABASE_URL = "https://gfpksdqblblnvkyiopcc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmcGtzZHFibGJsbnZreWlvcGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1Njk0NjIsImV4cCI6MjA3ODE0NTQ2Mn0.c1coL9Nppq_loiwNdb1Db_49SKf1Eacm8mrpkp0pRD0"